branch-defaults:
  main:
    environment: deployment-project-dev
    group_suffix: null
  master:
    environment: deployment-project-dev
    group_suffix: null
  staging:
    environment: staging-api
    group_suffix: null
deploy:
  artifact: ./udagram/udagram-api/www/Archive.zip
  main:
    environment: deployment-project-dev
    group_suffix: null
environment-defaults:
  deployment-project-dev:
    branch: null
    repository: null
global:
  application_name: deployment-project
  branch: null
  default_ec2_keyname: null
  default_platform: Node.js
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: default
  repository: null
  sc: git
  workspace_type: Application
